/*
 * HLDM_CONFIG_H_
 *
 * Created: 5/11/2016 12:34:55 AM
 *  Author: Abdo_Hijazi
 */

#ifndef HLDM_CONFIG_H_
#define HLDM_CONFIG_H_

#define HLDM_ROW0_PIN   MGPIO_u8_PORTA,0
#define HLDM_ROW1_PIN   MGPIO_u8_PORTA,1
#define HLDM_ROW2_PIN   MGPIO_u8_PORTA,2
#define HLDM_ROW3_PIN   MGPIO_u8_PORTA,3
#define HLDM_ROW4_PIN   MGPIO_u8_PORTA,4
#define HLDM_ROW5_PIN   MGPIO_u8_PORTA,5
#define HLDM_ROW6_PIN   MGPIO_u8_PORTA,6
#define HLDM_ROW7_PIN   MGPIO_u8_PORTA,7

#define HLDM_COL0_PIN   MGPIO_u8_PORTB,8
#define HLDM_COL1_PIN   MGPIO_u8_PORTB,9
#define HLDM_COL2_PIN   MGPIO_u8_PORTB,10
#define HLDM_COL3_PIN   MGPIO_u8_PORTB,11
#define HLDM_COL4_PIN   MGPIO_u8_PORTB,12
#define HLDM_COL5_PIN   MGPIO_u8_PORTB,13
#define HLDM_COL6_PIN   MGPIO_u8_PORTB,14
#define HLDM_COL7_PIN   MGPIO_u8_PORTB,15

#endif /* HLDM_CONFIG_H_ */
